Fixed element not interactable error
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=127.0.6533.122)

WebDriverWait was not the solution, needed to send , Keys.RETURN to make sure the action has immediate effect on the GUI.